---
# Source: nfs-client-provisioner/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Helm
    release: nfs-client
  name: nfs-client-nfs-client-provisioner
---
# Source: nfs-client-provisioner/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Helm
    release: nfs-client
  name: nfs-client
provisioner: cluster.local/nfs-client-nfs-client-provisioner
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "false"
---
# Source: nfs-client-provisioner/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Helm
    release: nfs-client
  name: nfs-client-nfs-client-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
# Source: nfs-client-provisioner/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Helm
    release: nfs-client
  name: run-nfs-client-nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-client-nfs-client-provisioner
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: nfs-client-nfs-client-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
# Source: nfs-client-provisioner/templates/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Helm
    release: nfs-client
  name: leader-locking-nfs-client-nfs-client-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
# Source: nfs-client-provisioner/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Helm
    release: nfs-client
  name: leader-locking-nfs-client-nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-client-nfs-client-provisioner
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: leader-locking-nfs-client-nfs-client-provisioner
  apiGroup: rbac.authorization.k8s.io
---
# Source: nfs-client-provisioner/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Helm
    release: nfs-client
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
      release: nfs-client
  template:
    metadata:
      annotations:
      labels:
        app: nfs-client-provisioner
        release: nfs-client
    spec:
      serviceAccountName: nfs-client-nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: "quay.io/external_storage/nfs-client-provisioner:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cluster.local/nfs-client-nfs-client-provisioner
            - name: NFS_SERVER
              value: storage
            - name: NFS_PATH
              value: /home/rnbj/kubedata
      volumes:
        - name: nfs-client-root
          nfs:
            server: storage
            path: /home/rnbj/kubedata
